/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AddGameModal: typeof import('./components/AddGameModal.vue')['default']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AlertBanner: typeof import('./components/AlertBanner.vue')['default']
    AnimatedCharacters: typeof import('./components/login/AnimatedCharacters.vue')['default']
    AppNavigationMenu: typeof import('./components/AppNavigationMenu.vue')['default']
    AppNavigationMenuNode: typeof import('./components/AppNavigationMenuNode.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    BannerCropModal: typeof import('./components/edit-game/BannerCropModal.vue')['default']
    CardRow: typeof import('./components/CardRow.vue')['default']
    CoverBannerSelectorModal: typeof import('./components/edit-game/import-modals/CoverBannerSelectorModal.vue')['default']
    DashboardHero: typeof import('./components/dashboard/DashboardHero.vue')['default']
    EditGameAssetImportModals: typeof import('./components/edit-game/EditGameAssetImportModals.vue')['default']
    EditGameModal: typeof import('./components/EditGameModal.vue')['default']
    EditGameWikiMetadataPickerModal: typeof import('./components/edit-game/EditGameWikiMetadataPickerModal.vue')['default']
    EyeBall: typeof import('./components/login/EyeBall.vue')['default']
    FileBrowserModal: typeof import('./components/FileBrowserModal.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameCarousel: typeof import('./components/GameCarousel.vue')['default']
    GameFilePathsSection: typeof import('./components/edit-game/GameFilePathsSection.vue')['default']
    GameMediaSection: typeof import('./components/edit-game/GameMediaSection.vue')['default']
    GameRowSection: typeof import('./components/dashboard/GameRowSection.vue')['default']
    LogoSelectorModal: typeof import('./components/edit-game/import-modals/LogoSelectorModal.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer.vue')['default']
    MediaManagementPanel: typeof import('./components/edit-game/MediaManagementPanel.vue')['default']
    MediaScreenshotSection: typeof import('./components/edit-game/MediaScreenshotSection.vue')['default']
    MetroTile: typeof import('./components/start-screen/MetroTile.vue')['default']
    PendingOverview: typeof import('./components/dashboard/PendingOverview.vue')['default']
    Pupil: typeof import('./components/login/Pupil.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenshotCarousel: typeof import('./components/ScreenshotCarousel.vue')['default']
    ScreenshotSelectorModal: typeof import('./components/edit-game/import-modals/ScreenshotSelectorModal.vue')['default']
    SharedAmbientBackground: typeof import('./components/SharedAmbientBackground.vue')['default']
    StartScreen: typeof import('./components/start-screen/StartScreen.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    StatOverview: typeof import('./components/dashboard/StatOverview.vue')['default']
    SteamSearchPanel: typeof import('./components/SteamSearchPanel.vue')['default']
    SummaryImportModal: typeof import('./components/edit-game/import-modals/SummaryImportModal.vue')['default']
    TileCropModal: typeof import('./components/start-screen/TileCropModal.vue')['default']
    WikiEditor: typeof import('./components/WikiEditor.vue')['default']
    WikiToc: typeof import('./components/WikiToc.vue')['default']
  }
}
